import Head from 'next/head'
import { Header } from '../layouts/home/header'
import { Positions } from '../layouts/home/positions'
import { Skillset } from '../layouts/home/skillset'

export default function Home() {
  return (
    <>
      <Head>
        <title>
					Kenny Vallejo | Fullstack Developer
				</title>
        <meta 
					name="description" 
					content="Generated by create next app" 
				/>
        <link 
					rel="icon" 
					href="/favicon.ico" 
				/>
      </Head>
			{/* 
				Header, Includes:
				- Navigation Bar
				- Biography
				- Profile Picture
				- Scroll Button 
			*/}
			<Header />

			{/* 
				Positions, Includes: 
				- Section Label
				- Position Card
			*/}
			<Positions />

			{/* 
				Skillset, Includes: 
				- Section Label
				- Skills and Knowledge (Simple List)	
				- Tools and technologies (Complex List)
				- Spoken Languages (Simple List)	
			*/}
			<Skillset />
    </>
  )
}
