import Head from 'next/head'
import { Header } from '../layouts/home/header'

export default function Home() {
  return (
    <>
      <Head>
        <title>
					Kenny Vallejo | Fullstack Developer
				</title>
        <meta 
					name="description" 
					content="Generated by create next app" 
				/>
        <link 
					rel="icon" 
					href="/favicon.ico" 
				/>
      </Head>

			<Header />
    </>
  )
}
